Using Ubuntu 13.04: libppl.a seems to require libm for linking:
libtool: link: gcc -Wall -fomit-frame-pointer -g -O2 -o cloog cloog.o  -L<builddir>/installed-libs-for-cross-gcc/lib ./.libs/libcloog.a <builddir>/installed-libs-for-cross-gcc/lib/libppl_c.a <builddir>/installed-libs-for-cross-gcc/lib/libppl.a <builddir>/installed-libs-for-cross-gcc/lib/libgmpxx.a <builddir>/installed-libs-for-cross-gcc/lib/libgmp.a -lstdc++
/usr/bin/ld: <builddir>/installed-libs-for-cross-gcc/lib/libppl.a(Init.o): undefined reference to symbol 'fegetround@@GLIBC_2.2.5'
/usr/bin/ld: note: 'fegetround@@GLIBC_2.2.5' is defined in DSO /lib/x86_64-linux-gnu/libm.so.6 so try adding it to the linker command line
/lib/x86_64-linux-gnu/libm.so.6: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status

Fix by manually adding libm to cloog/cc1 link lines.